// Generated by gencpp from file imu_comm/imu_info.msg
// DO NOT EDIT!


#ifndef IMU_COMM_MESSAGE_IMU_INFO_H
#define IMU_COMM_MESSAGE_IMU_INFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace imu_comm
{
template <class ContainerAllocator>
struct imu_info_
{
  typedef imu_info_<ContainerAllocator> Type;

  imu_info_()
    : header()
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , acc_vel_x(0.0)
    , acc_vel_y(0.0)
    , acc_vel_z(0.0)  {
    }
  imu_info_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , acc_vel_x(0.0)
    , acc_vel_y(0.0)
    , acc_vel_z(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _roll_type;
  _roll_type roll;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _acc_vel_x_type;
  _acc_vel_x_type acc_vel_x;

   typedef float _acc_vel_y_type;
  _acc_vel_y_type acc_vel_y;

   typedef float _acc_vel_z_type;
  _acc_vel_z_type acc_vel_z;





  typedef boost::shared_ptr< ::imu_comm::imu_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imu_comm::imu_info_<ContainerAllocator> const> ConstPtr;

}; // struct imu_info_

typedef ::imu_comm::imu_info_<std::allocator<void> > imu_info;

typedef boost::shared_ptr< ::imu_comm::imu_info > imu_infoPtr;
typedef boost::shared_ptr< ::imu_comm::imu_info const> imu_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::imu_comm::imu_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::imu_comm::imu_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace imu_comm

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'imu_comm': ['/home/heeseok/imu_ws/src/imu_comm/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::imu_comm::imu_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_comm::imu_info_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_comm::imu_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_comm::imu_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_comm::imu_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_comm::imu_info_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::imu_comm::imu_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "993d23e4a6233100e734c2ee81c2ee9a";
  }

  static const char* value(const ::imu_comm::imu_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x993d23e4a6233100ULL;
  static const uint64_t static_value2 = 0xe734c2ee81c2ee9aULL;
};

template<class ContainerAllocator>
struct DataType< ::imu_comm::imu_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imu_comm/imu_info";
  }

  static const char* value(const ::imu_comm::imu_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::imu_comm::imu_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
float32 roll\n\
float32 pitch\n\
float32 yaw\n\
float32 acc_vel_x\n\
float32 acc_vel_y\n\
float32 acc_vel_z\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::imu_comm::imu_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::imu_comm::imu_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.acc_vel_x);
      stream.next(m.acc_vel_y);
      stream.next(m.acc_vel_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct imu_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imu_comm::imu_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::imu_comm::imu_info_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "acc_vel_x: ";
    Printer<float>::stream(s, indent + "  ", v.acc_vel_x);
    s << indent << "acc_vel_y: ";
    Printer<float>::stream(s, indent + "  ", v.acc_vel_y);
    s << indent << "acc_vel_z: ";
    Printer<float>::stream(s, indent + "  ", v.acc_vel_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMU_COMM_MESSAGE_IMU_INFO_H
