# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from imu_comm/imu_info.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class imu_info(genpy.Message):
  _md5sum = "68254290c37f4da9714737632b52b84a"
  _type = "imu_comm/imu_info"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header

float32 roll
float32 pitch
float32 yaw

float32 acc_gyro_roll
float32 acc_gyro_pitch
float32 acc_gyro_yaw

float32 acc_vel_x
float32 acc_vel_y
float32 acc_vel_z
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id
"""
  __slots__ = ['header','roll','pitch','yaw','acc_gyro_roll','acc_gyro_pitch','acc_gyro_yaw','acc_vel_x','acc_vel_y','acc_vel_z']
  _slot_types = ['std_msgs/Header','float32','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,roll,pitch,yaw,acc_gyro_roll,acc_gyro_pitch,acc_gyro_yaw,acc_vel_x,acc_vel_y,acc_vel_z

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(imu_info, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.roll is None:
        self.roll = 0.
      if self.pitch is None:
        self.pitch = 0.
      if self.yaw is None:
        self.yaw = 0.
      if self.acc_gyro_roll is None:
        self.acc_gyro_roll = 0.
      if self.acc_gyro_pitch is None:
        self.acc_gyro_pitch = 0.
      if self.acc_gyro_yaw is None:
        self.acc_gyro_yaw = 0.
      if self.acc_vel_x is None:
        self.acc_vel_x = 0.
      if self.acc_vel_y is None:
        self.acc_vel_y = 0.
      if self.acc_vel_z is None:
        self.acc_vel_z = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.roll = 0.
      self.pitch = 0.
      self.yaw = 0.
      self.acc_gyro_roll = 0.
      self.acc_gyro_pitch = 0.
      self.acc_gyro_yaw = 0.
      self.acc_vel_x = 0.
      self.acc_vel_y = 0.
      self.acc_vel_z = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_9f().pack(_x.roll, _x.pitch, _x.yaw, _x.acc_gyro_roll, _x.acc_gyro_pitch, _x.acc_gyro_yaw, _x.acc_vel_x, _x.acc_vel_y, _x.acc_vel_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 36
      (_x.roll, _x.pitch, _x.yaw, _x.acc_gyro_roll, _x.acc_gyro_pitch, _x.acc_gyro_yaw, _x.acc_vel_x, _x.acc_vel_y, _x.acc_vel_z,) = _get_struct_9f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_9f().pack(_x.roll, _x.pitch, _x.yaw, _x.acc_gyro_roll, _x.acc_gyro_pitch, _x.acc_gyro_yaw, _x.acc_vel_x, _x.acc_vel_y, _x.acc_vel_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 36
      (_x.roll, _x.pitch, _x.yaw, _x.acc_gyro_roll, _x.acc_gyro_pitch, _x.acc_gyro_yaw, _x.acc_vel_x, _x.acc_vel_y, _x.acc_vel_z,) = _get_struct_9f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_9f = None
def _get_struct_9f():
    global _struct_9f
    if _struct_9f is None:
        _struct_9f = struct.Struct("<9f")
    return _struct_9f
